[tool.poetry]
name = "kyrsovya-4"
version = "0.1.0"
description = ""
authors = ["dinar valeev <dinarvaleev513@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
pytest = "^8.3.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
